//
//  PatternInsights.swift
//  Pulse
//
//  Created by Marcus Raitner on 09.10.26.
//

import FoundationModels

/// Structured output generated by Apple Intelligence when analysing log entry patterns.
/// The three arrays map directly to the three sections shown in ``InsightsView``.
@Generable
struct PatternInsights {
    @Guide(description: "Up to 3 synthesised insights — NOT a list of entries — explaining what underlying theme or condition made high-scoring moments (+1/+2) great. Each item names a recurring pattern and briefly explains why it mattered, e.g. 'Physical activity consistently lifts mood: workouts and walks appear in nearly all +2 entries.'")
    var greatMoments: [String]

    @Guide(description: "Up to 3 synthesised insights — NOT a list of entries — explaining what underlying theme or condition drove low-scoring moments (-1/-2). Each item names a recurring pattern and briefly explains the impact, e.g. 'Lack of sleep amplifies stress: most -2 entries mention tiredness combined with a demanding task.'")
    var poorMoments: [String]

    @Guide(description: "Up to 3 concrete, personalised actions derived from the patterns above. Each tip is directly actionable and specific to the data, e.g. 'Schedule at least one outdoor activity on days with back-to-back meetings to counteract the recurring stress pattern.'")
    var actionableTips: [String]
}
